# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -project SafeDataStructureKit.xcodeproj -scheme SafeDataStructureKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
